### ISSUE TITLE
stretching receptors for some reason

### ISSUE THREAD

**Issue by azaelvsrg** [Kizuna-dev/Osu-Auto-Receptor#1]
https://imgur.com/coYBr2i
ik nothing abt coding but this issue so hi

**Comment by Kizuna-dev** [comment]
That's the point of the program tho. 

Because osu are stretching your image, when you import clean receptor, it will looks stretched and horrible in game, this program stretch itself the image to make it ready for osu, aka, when seeing it on osu, it will looks exactly like it is a normal receptor.

You can even notice that on popular skin, if you were to look at the receptor image, you will see they are weirdly stretched, it's simply to make it looks good ingame.

Tho be mindful you **NEED** to have the clean image version of your receptor first, you can't change one that has already been changed.

**Comment by azaelvsrg** [comment]
it doesn't look normal in game though, it looks just as stretched, which is pretty easy to tell its not normal

**Comment by azaelvsrg** [comment]
1. yes
2. yes
3. idek what that means

**Comment by Kizuna-dev** [comment]
![sss](https://user-images.githubusercontent.com/68703144/136719177-10eca108-7b52-47f2-86d5-b5bfbc5e675f.png)

Hope that's understandable simply with this image, but basically : Clean = normal unchanged image / Not clean = already stretched, as you can see on the receptor, the height is way bigger, and there is lot of empty space below

**Comment by azaelvsrg** [comment]
ok ty
